# Example server configuration for DVID

[server]
# Who to send email in case of panic
notify = ["foo@someplace.edu"]

    [server.logging]
    logfile = "/demo/logs/dvid.log"
    max_log_size = 500 # MB
    max_log_age = 30   # days

    # Email server to use for notifications and server issuing email-based authorization tokens.
    [server.email]
    username = 
    password = 
    server = 
    port = 25

