# Example configuration for DVID

[server]
httpAddress = "localhost:8000"
rpcAddress = "localhost:8001"
webClient = "/path/to/webclient"

# to return Timing-Allow-Origin headers in response
# allowTiming = true

# How new data instance ids are generated.
# Is one of "random" or "sequential".  If "sequential" can set "start_instance_id" property.
instance_id_gen = "sequential"
instance_id_start = 100  # new ids start at least from this.

# Email server to use for notifications and server issuing email-based authorization tokens.
#[email]
#notify = ["foo@someplace.edu"] # Who to send email in case of panic
#username = 
#password = 
#server = 
#port = 25

[logging]
logfile = "/demo/logs/dvid.log"
max_log_size = 500 # MB
max_log_age = 30   # days

[store]   
    # if no store.metadata is provided, it defaults to store.mutable configuration
    [store.mutable]
    engine = "basholeveldb"
    path = "/demo/dbs/basholeveldb"

    [store.immutable]
    engine = "kvautobus"
    path = "http://tem-dvid.int.janelia.org:9000"